# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/blenderproc-test-scenes',
                'doc_host': 'https://flupppi.github.io',
                'git_url': 'https://github.com/flupppi/blenderproc-test-scenes',
                'lib_path': 'blenderproc_test_scenes'},
  'syms': {'blenderproc_test_scenes.core': {'blenderproc_test_scenes.core.foo': ('core.html#foo', 'blenderproc_test_scenes/core.py')}}}
